### ISSUE TITLE
dlr-sc OSX conda package has incorrect linked libfreeimage.dylib

### ISSUE THREAD

**Issue by jf---** [tpaviot/pythonocc-contrib#14]
note how **libfreeimage-3.17.0.dylib** is linked, while **libfreeimage.3.17.0.dylib** is installed ( see the "-" ). copying the library to **libfreeimage-3.17.0.dylib** resolves the issue.

**Comment by jf---** [comment]
@rainman110 a way to temporary take packages offline is by moving them to a /develop channel

**Comment by jf---** [comment]
note how **libfreeimage-3.17.0.dylib** is linked, while **libfreeimage.3.17.0.dylib ** is installed ( see the "-" ). copying the lib with the correct name doesnt resolve the issue alas...

**Comment by rainman110** [comment]
@jf--- Somehow, all the infos to this bug are gone?! I have them in may mail account, but where are they here?

I could not completely understand the problem. Somehow, freeimage is incorrectly linked. Strangely, on my mac the packages worked. Can you again post the output of otool -L _AIS.so of my package and of yours?

@rpath/./libfreeimage-3.17.0.dylib seems to be correct, or not? That should look inside $PREFIX/lib for libfreeimage.dylib.

How did you rewrite the libs to use @loader_path? 

I am a bloody beginner, when it comes to rpath / loader_path handing on the mac.

**Comment by jf---** [comment]
> @jf--- Somehow, all the infos to this bug are gone?! I have them in may mail account, but where are they here?

Well, I found out about the "-" issue later than my earlier ramblings... your @rpath approach is simple and works perfect. Its the "-" in the libfreeimage path name that's the problem. I just rebuild your recipe for libfreeimage locally 5 min ago and when I use that, all is peachy...

So I'm a little lost why I couldnt install it correct in the first place...
Sorry for the noise...

> @rpath/./libfreeimage-3.17.0.dylib seems to be correct, or not?

Yes, though the package I installed from did not have this exact link. So I'll double check if I this lib didnt come from another repo...

> I am a bloody beginner, when it comes to rpath / loader_path handing on the mac.

Same here, but excuse my FUD! yours is fine...

**Comment by jf---** [comment]
So here we go:
- I removed my channel from ~/.condarc such to make sure all dependencies are loaded from either your or default channel

``` bash
517 ~~~:freeimage$ nano ~/condarc
518 ~~~:freeimage$ nano ~/.condarc
519 ~~~:freeimage$ source activate dlr-check
discarding /Users/~~~/miniconda/bin from PATH
prepending /Users/~~~/miniconda/envs/dlr-check/bin to PATH
(dlr-check)520 ~~~:freeimage$ conda install pythonocc-core
Fetching package metadata: ....................
Solving package specifications: ..........
Package plan for installation in environment /Users/~~~/miniconda/envs/dlr-check:

The following NEW packages will be INSTALLED:

    freeimage:      3.17.0-0         dlr-sc  
    freetype:       2.5.5-0          defaults
    gl2ps:          1.3.8-0          dlr-sc  
    libpng:         1.6.17-0         asmeurer
    oce:            0.16.1-1         dlr-sc  
    pyqt:           4.11.4-py27_1    defaults
    pythonocc-core: 0.16.3dev-py27_0 dlr-sc  
    qt:             4.8.7-1          defaults
    sip:            4.16.9-py27_0    defaults
    tbb:            4.3.6-0          dlr-sc  

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|########################################################################################| 100%
(dlr-check)521 ~~~:freeimage$ py /Users/~~~/GIT/pythonocc-core/examples/core_geometry_airfoil.py 
Traceback (most recent call last):
  File "/Users/~~~/GIT/pythonocc-core/examples/core_geometry_airfoil.py", line 107, in <module>
    display, start_display, add_menu, add_function_to_menu = init_display()
  File "/Users/~~~/miniconda/envs/dlr-check/lib/python2.7/site-packages/OCC/Display/SimpleGui.py", line 109, in init_display
    from OCC.Display.qtDisplay import qtViewer3d, get_qt_modules
  File "/Users/~~~/miniconda/envs/dlr-check/lib/python2.7/site-packages/OCC/Display/qtDisplay.py", line 23, in <module>
    from OCC.Display import OCCViewer
  File "/Users/~~~/miniconda/envs/dlr-check/lib/python2.7/site-packages/OCC/Display/OCCViewer.py", line 26, in <module>
    from OCC.AIS import AIS_MultipleConnectedInteractive, AIS_Shape
  File "/Users/~~~/miniconda/envs/dlr-check/lib/python2.7/site-packages/OCC/AIS.py", line 32, in <module>
    _AIS = swig_import_helper()
  File "/Users/~~~/miniconda/envs/dlr-check/lib/python2.7/site-packages/OCC/AIS.py", line 28, in swig_import_helper
    _mod = imp.load_module('_AIS', fp, pathname, description)
ImportError: dlopen(/Users/~~~/miniconda/envs/dlr-check/lib/python2.7/site-packages/OCC/_AIS.so, 2): Library not loaded: @rpath/./libfreeimage-3.17.0.dylib
  Referenced from: /Users/~~~/miniconda/envs/dlr-check/lib/python2.7/site-packages/OCC/_AIS.so
  Reason: image not found
(dlr-check)522 ~~~:freeimage$ 
```

Now, I rebuild your freeimage recipe ( no changes whatsoever... ) 

``` bash
(dlr-check)522 jelleferinga:freeimage$ conda install freeimage --use-local
Fetching package metadata: ......................
Solving package specifications: ......
Package plan for installation in environment /Users/jelleferinga/miniconda/envs/dlr-check:

The following packages will be UPDATED:

    freeimage: 3.17.0-0 dlr-sc --> 3.17.0-3 file:///Users/jelleferinga/miniconda/conda-bld/osx-64/

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE      ]|########################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|########################################################################################| 100%
(dlr-check)523 jelleferinga:freeimage$ py /Users/jelleferinga/GIT/pythonocc-core/examples/core_geometry_airfoil.py 
Using PyQt4
 ###### 3D rendering pipe initialisation #####
Display3d class initialization starting ...
Aspect_DisplayConnection created.
Graphic_Driver created.
Cocoa window created.
V3d_Viewer created.
V3d_View created
AIS_InteractiveContext created.
Display3d class successfully initialized.
 ########################################
(dlr-check)524 jelleferinga:freeimage$ 
```

So the issue is that the DLR freeimage package does not have **libfreeimage-3.17.0.dylib** and the newly build package does have this... 

OK, that's the 1st really strange case in conda thusfar :sunglasses:

**Comment by jf---** [comment]
literally, on the build nr is changed...

**Comment by jf---** [comment]
hi @rainman110 ,

Well, the point with conda is to be able to reproduce, right ;)
I've added the results of your libfreeimage recipe to my anaconda channel:

``` bash
conda install -c https://conda.anaconda.org/jf freeimage
```

**Comment by rainman110** [comment]
hm... this is really strange. i just downloaded my freeimage osx package, and the library seems  to be there:
![freeimageosx](https://cloud.githubusercontent.com/assets/3213107/11715540/025abccc-9f43-11e5-8bdf-d8b0204859a2.png)

**Comment by rainman110** [comment]
@jf--- could you please do the same test again. I am sure, the library must be in there. i suspect conda to mix my package up with some old package, or one of yours? Maybe I changed once the package without increasing the build number. therefore conda does not redownload from dlr-sc, but just fetches the package from the cache.

Therefore, can you first clean the conda package cache also:

```
 conda clean --packages
```

**Comment by jf---** [comment]
Hi @rainman110 ,

I think the suspicion that this is a local ( but reproducable ) issue...
Thanks for the clean package hint, I'll try this on a clean machine later today.

**Comment by rainman110** [comment]
@jf--- Did you check again this issue? Can we close it?

**Comment by jf---** [comment]
Lets close it, I cannot pinpoint the issue sufficiently precise to make it actionable...
