### ISSUE TITLE
conda support for py3k

### ISSUE THREAD

**Issue by tpaviot** [tpaviot/pythonocc-contrib#17]
current conda packages support py27 only, we should consider adding py3k support.

**Comment by jf---** [comment]
:+1: , this was achieved for the original recipe that build for 2.7 and 3.4, so that's a regression indeed...

**Comment by rainman110** [comment]
Yes this is true. But I don't think, that the packages are restricted to python2.7. Are they?

**Comment by rainman110** [comment]
I added all required py34 packages to [Anaconda/DLR-SC](https://anaconda.org/DLR-SC/) and updated the recipes at https://github.com/DLR-SC/tigl-conda. Will merge back the changes asap.

**Comment by tpaviot** [comment]
fixed. tested.
