### ISSUE TITLE
Can't install pythonocc-core through Anaconda3's conda

### ISSUE THREAD

**Issue by huskier** [tpaviot/pythonocc-contrib#7]
@jf--- 
Dear Jelle, 
I follow your instructions to install pythonocc-core. When I execute the following line:

```
conda install pythonocc-core
```

An error occured, an it reads:
Error: No packages found in current linux-64 channels matching: pythonocc-core

Is the pythonocc-core ready for conda?

**Comment by jf---** [comment]
hi @huskier 

Correct, at the moment, the conda installer only works for OSX, windows support is in the works and linux long overdue, since this should be pretty straightfwd. I'll spend some time this weekend to get going on this. I'll get back to this topic when ready for testing.

**Comment by jf---** [comment]
hi @huskier ,

recently @rainman110 contributed a [linux package](https://anaconda.org/DLR-SC/pythonocc-core).
actually, much better news: pythonocc-core packages are now available on linux ( 32/64 ), osx ( 64 ) and windows ( 32 / 64 ) 
could you try and run:

``` bash
conda install -c https://conda.anaconda.org/dlr-sc pythonocc-core
```

Looking fwd hearing from you...

**Comment by huskier** [comment]
@jf---  FYI
Successful on Scientific Linux 6.0 (much like CentOS 6.0) with Anaconda 2.1.0

but failed on Windows XP with Anaconda 2.1.0, The info as follows, and the error occurs during linking packages...
Extracting packages ...
[ COMPLETE ] |###################################################| 100%
Unlinking packages ...
[ COMPLETE ] |###################################################| 100%
Linking packages ...
System can not find the file specified |###################      |  63%
Error: Error: post-link failed for: pyqt-4.11.4-py27_4

**Comment by jf---** [comment]
Cool, happy to hear so @huskier , thanks for reporting...
Wrt XP, this OS is no longer maintained, and I've managed to install in windows 7...
I think we should pass on XP support.
Good to know nonetheless.
Btw, looks like failing on pyqt rather than pythonocc-core...

**Comment by huskier** [comment]
@jf--- 
Thanks.
